Update backend_deploy.yaml

diff --git a/.github/workflows/backend_deploy.yaml b/.github/workflows/backend_deploy.yaml
--- a/.github/workflows/backend_deploy.yaml
+++ b/.github/workflows/backend_deploy.yaml
@@ -63,7 +63,11 @@ jobs:
           if [ "$debug_mode" = "true" ]; then
             pnpm run deploy
           else
-            pnpm run deploy
+           output=$(pnpm run deploy 2>&1)
+            if [ $? -ne 0 ]; then
+                code=$?
+                echo "Command failed with exit code $code"
+                exit $code
             fi
           fi
           echo "Deployed for tag ${{ github.ref_name }}"
